### ISSUE TITLE
BlitzcordRunCallbacks Ends the b3d program.

### ISSUE THREAD

**Issue by funniman-exe** [AestheticalZ/Blitzcord#2]
Simple as that, when launching the program, it states "Program has ended" with the debugger showing BlitzcordRunCallbacks() as the cause.

If the function is in a repeat loop, it throws a memory access violation instead.

**Comment by AnalogFeelings** [comment]
Is the program able to access the discord SDK DLL?

**Comment by funniman-exe** [comment]
Yes it is. If i use the one from the x86 folder it does as explained, if i use the one from the x86_64 folder, it doesn't find the userlib.

**Comment by AnalogFeelings** [comment]
32-bit programs cannot use 64-bit DLLs.

**Comment by AnalogFeelings** [comment]
Are you using the TSS fork?

**Comment by funniman-exe** [comment]
TSS? Yes?? im trying to implement it into a scpcb mod im making.

**Comment by funniman-exe** [comment]
are you referring to blitzcord or b3d itself

**Comment by AnalogFeelings** [comment]
Can you send a code sample that can replicate the issue?

**Comment by funniman-exe** [comment]
`BlitzcordCreateCore("IDNAMEHERE")`

`Function UpdateBlitzcord(gameStatus=0)`
`	If (gameStatus=0) Then`
`		BlitzcordSetLargeImage( "temp_icn" )`
`		BlitzcordSetSmallImage( "" )`
`		BlitzcordSetActivityDetails( "test" )`
`		BlitzcordSetActivityState( "test" )`
`		;BlitzcordSetTimestampStart( "0" )`
`	ElseIf (gameStatus=1)`
`		BlitzcordSetLargeImage( "temp_icn" )`
`		BlitzcordSetSmallImage( "" )`
`		BlitzcordSetActivityDetails( "" )`
`		BlitzcordSetActivityState( "Main Menu" )`
`		;BlitzcordSetTimestampStart( "0" )`
`	ElseIf (gameStatus=2)`
`		BlitzcordSetLargeImage( "temp_icn" )`
`		BlitzcordSetSmallImage( "" )`
`		BlitzcordSetActivityDetails( "Map:" )`
`		BlitzcordSetActivityState( "In Game" )`
`		;BlitzcordSetTimestampStart( "0" )`
`	ElseIf (gameStatus=3)`
`		BlitzcordSetLargeImage( "temp_icn" )`
`		BlitzcordSetSmallImage( "" )`
`		BlitzcordSetActivityDetails( "Loading..." )`
`		BlitzcordSetActivityState( "" )`
`		;BlitzcordSetTimestampStart( "0" )`
`	EndIf`
`	BlitzcordUpdateActivity()`
`	BlitzcordRunCallbacks()`
`End Function`

`Repeat`
`	UpdateBlitzcord()`
`Forever`

**Comment by AnalogFeelings** [comment]
Do you have the discord SDK DLL next to blitzcc? Otherwise it will not be able to load it when running the game without an exe

**Comment by funniman-exe** [comment]
![image](https://github.com/AnalogFeelings/Blitzcord/assets/112577221/8c182939-bb3d-474b-84c5-47675e2eccf4)

**Comment by AnalogFeelings** [comment]
I'll take a look at it later

**Comment by funniman-exe** [comment]
Even if i build it into an exe, it throws a memory access violation.

**Comment by VaneBrain** [comment]
> ![image](https://user-images.githubusercontent.com/112577221/265121108-8c182939-bb3d-474b-84c5-47675e2eccf4.png)

Did you put this .delcs file in the userlibs folder of Blitz3D? Because the screenshot shows Bin folder

**Comment by funniman-exe** [comment]
yes
![image](https://github.com/AnalogFeelings/Blitzcord/assets/112577221/4ed91346-d9a6-4a05-ab22-09130e70ecd2)

**Comment by funniman-exe** [comment]
Is there any way to fix this?

**Comment by funniman-exe** [comment]
Holy crap i just fixed it, turns out the discord_game_sdk dll was being shitty. I transfered the one from scp-ntf and it works now.
